### ISSUE TITLE
Move to JuliaArchive?

### ISSUE THREAD

**Issue by sbromberger** [sbromberger/Centrality.jl#2]
@tkelman - could we move this to JuliaArchive? It's tied to Graphs.jl and is no longer maintained, but someone might have a use for it.

**Comment by tkelman** [comment]
I suppose. Is there any harm leaving it here?

**Comment by sbromberger** [comment]
No special harm; I just don't like having deprecated packages hanging out here. I suppose I could just deregister it... not sure anyone's even using it (and they shouldn't since I'm not even sure these measures are efficient/correct anymore).

**Comment by tkelman** [comment]
I've already said elsewhere, if anyone has installed or used the package, then you shouldn't deregister it. That's only ever done if something was a complete mistake. You can add Julia upper bounds to all past tagged versions if you want to officially deprecate the package.

**Comment by sbromberger** [comment]
OK, thanks. I may need your help with adding the upper bounds. I don't know what's appropriate: would 0.3 be too aggressive? (Also, what's the process for retroactively adding these upper bounds?)

**Comment by tkelman** [comment]
Yes 0.3 would be much too strong. Best to do `0.5` if you're quick about it. It would be a pull request to METADATA where you edit the `requires` files for all the existing tags of the package.

**Comment by sbromberger** [comment]
Sorry - so, for each tag, I check out that code, modify the requires, then `Pkg.publish()`?

**Comment by tkelman** [comment]
No, the change is entirely to METADATA.

**Comment by sbromberger** [comment]
oh, got it, I think. OK. let me see what I can do.

Does this change the hashes that are associated with the tags?

**Comment by tkelman** [comment]
No, don't touch the sha1 file contents.

**Comment by sbromberger** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/6166

**Comment by sbromberger** [comment]
Closing via https://github.com/JuliaLang/METADATA.jl/pull/6166
